ALTER TABLE TASKS
    ADD CONSTRAINT chk_status
        CHECK(STATUS IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDO', 'COM_IMPEDIMENTO')),
    ADD CONSTRAINT chk_prioridade
        CHECK(PRIORIDADE IN ('BAIXA', 'MEDIA', 'ALTA', 'URGENTE')),
    ALTER COLUMN PRAZO TYPE TIMESTAMP(2),
    ALTER COLUMN DATA_CRIACAO TYPE TIMESTAMP(2),
    ALTER COLUMN ULTIMA_ATUALIZACAO TYPE TIMESTAMP(2);