ALTER TABLE TASKS
    ALTER COLUMN STATUS DROP DEFAULT,
    ALTER COLUMN PRIORIDADE DROP DEFAULT;

DROP TYPE STATUS_TASK, PRIORIDADE_TASK;

ALTER TABLE TASKS
    ALTER COLUMN STATUS SET DEFAULT 'PENDENTE',
    ALTER COLUMN PRIORIDADE SET DEFAULT 'BAIXA';
