CREATE TYPE STATUS_TASK AS ENUM(
    'PENDENTE',
    'EM_ANDAMENTO',
    'CONCLUIDA',
    'COM_IMPEDIMENTO'
);

CREATE TYPE PRIORIDADE_TASK AS ENUM(
    'BAIXA',
    'MEDIA',
    'ALTA',
    'URGENTE'
);

CREATE TABLE TASKS(
    ID UUID PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(150),
    STATUS STATUS_TASK NOT NULL DEFAULT 'PENDENTE',
    PRIORIDADE PRIORIDADE_TASK NOT NULL DEFAULT 'BAIXA',
    PRAZO TIMESTAMP NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    ULTIMA_ATUALIZACAO TIMESTAMP NOT NULL
);
